Justica2/Justica2/Models/NewsName.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Justica2.Models
{
    public class NewsName
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(100)]
        public string Name { get; set; }
        [ForeignKey("News")]
        public int NewsId { get; set; }
        public News News { get; set; }
    }
}

Justica2/Justica2/Areas/Admin/Controllers/NewsNameController.cs
using Justica2.Data;
using Justica2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Justica2.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "SuperAdmin,Admin")]
    public class NewsNameController : Controller
    {
        private readonly AppDbContext _context;

        public NewsNameController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int page = 1)
        {
            ViewBag.Active = "News";
            List<NewsName> news1 = _context.NewsNames.Include(w => w.News).ToList();
            decimal dataPage = 5;
            decimal pageCount = Math.Ceiling(news1.Count / dataPage);

            List<NewsName> news2 = news1.OrderByDescending(o => o.Id).Skip(Convert.ToInt32((page - 1) * dataPage)).Take((int)dataPage).ToList();
            ViewBag.CurrentPage = page;
            ViewBag.PageCount = pageCount;
            ViewBag.DataPage = dataPage;
            ViewBag.DataCount = news1.Count;
            return View(news2);
        }

        public IActionResult Create()
        {
            ViewBag.News = _context.News.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(NewsName model)
        {
            if (ModelState.IsValid)
            {
                _context.NewsNames.Add(model);
                _context.SaveChanges();
                ViewBag.News = _context.News.ToList();
                return RedirectToAction("Index");
            }
            ViewBag.News = _context.News.ToList();
            return View(model);
        }

        public IActionResult Update(int? newsId)
        {
            if (newsId == null && newsId <= 0)
            {
                ViewBag.News = _context.News.ToList();
                return NotFound();
            }
            NewsName news = _context.NewsNames.Find(newsId);
            ViewBag.News = _context.News.ToList();
            return View(news);
        }

        [HttpPost]
        public IActionResult Update(NewsName model)
        {
            if (ModelState.IsValid)
            {
                _context.NewsNames.Update(model);
                _context.SaveChanges();
                ViewBag.News = _context.News.ToList();
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Duzgun duzelt!");
            ViewBag.News = _context.News.ToList();
            return View();

        }

        public IActionResult Delete(int? newsId)
        {
            NewsName news = _context.NewsNames.Find(newsId);
            _context.NewsNames.Remove(news);
            _context.SaveChanges();
            ViewBag.News = _context.News.ToList();
            return RedirectToAction("Index");
        }
    }
}

Justica2/Justica2/Areas/Admin/Views/NewsName/Create.cshtml
@model NewsName
@{
    ViewData["Title"] = "Create";
}

<div class="intro-y flex items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Create News Name
    </h2>
</div>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 lg:col-span-6">
        <!-- BEGIN: Form Layout -->
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" style="color:red; margin-bottom:30px;"></div>
            <div class="intro-y box p-5">
                <div>
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="input w-full border mt-2">
                </div>
                <div class="mt-3">
                    <label asp-for="NewsId">Practice Area Name</label>
                    <div class="mt-2">
                        <select asp-for="NewsId" asp-items="@(new SelectList(ViewBag.News, "Id", "Name"))" data-placeholder="Select your favorite actors" class="select2 w-full">
                            <option selected="" disabled>Select Category</option>
                        </select>
                    </div>
                </div>
                <div class="text-right mt-5">
                    <a asp-area="admin" asp-controller="NewsName" asp-action="index" class="button w-24 border text-gray-700 mr-1">Cancel</a>
                    <button type="submit" class="button w-24 bg-theme-1 text-white">Create</button>
                </div>
            </div>
        </form>
        <!-- END: Form Layout -->
    </div>
</div>

Justica2/Justica2/Areas/Admin/Views/NewsName/Index.cshtml
@model List<NewsName>
@{
    ViewData["Title"] = "Index";
    int firstRow = (int)((ViewBag.CurrentPage - 1) * ViewBag.DataPage);
}

<h2 class="intro-y text-lg font-medium mt-10">
    News Name Data
</h2>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
        <a class="button text-white bg-theme-1 shadow-md mr-2" asp-area="Admin" asp-controller="NewsName" asp-action="Create">Add New News Name</a>

        <div class="hidden md:block mx-auto text-gray-600">Showing @(firstRow + 1) to @(firstRow + ViewBag.DataPage ) of @ViewBag.DataCount entries</div>

    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <table class="table table-report -mt-2">
            <thead>
                <tr>
                    <th class="whitespace-no-wrap">#</th>
                    <th class="text-center whitespace-no-wrap">Name</th>
                    <th class="text-center whitespace-no-wrap">News Name</th>
                    <th class="text-center whitespace-no-wrap">Action</th>
                </tr>
            </thead>
            <tbody>
                @{ int i = firstRow;}
                @foreach (var item in Model)
                {
                    i++;
                    <tr class="intro-x">
                        <td class="w-40">
                            @i
                        </td>

                        <td class="text-center">@item.Name</td>
                        <td class="text-center">@item.News.Name</td>
                        <td class="w-40">
                            <div class="flex items-center justify-center text-theme-9"> <i data-feather="check-square" class="w-4 h-4 mr-2"></i> Active </div>
                        </td>
                        <td class="table-report__action w-56">
                            <div class="flex justify-center items-center">
                                <a class="flex items-center mr-3" asp-area="admin" asp-controller="NewsName" asp-action="update" asp-route-newsId="@item.Id"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                                <a class="flex items-center text-theme-6" asp-area="admin" asp-controller="NewsName" asp-action="delete" asp-route-newsId="@item.Id" onclick="return confirm('Are you sure?')"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- END: Data List -->
    <!-- BEGIN: Pagination -->
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-no-wrap items-center">
        <ul class="pagination">
            <li>
                <a class="pagination__link" asp-area="Admin" asp-controller="NewsName" asp-action="index" asp-route-page="1"> <i class="w-4 h-4" data-feather="chevrons-left"></i> </a>
            </li>
            <li>
                <a class="pagination__link" asp-area="Admin" asp-controller="NewsName" asp-action="index" asp-route-page="@(ViewBag.CurrentPage<=1?1: ViewBag.CurrentPage - 1)"> <i class="w-4 h-4" data-feather="chevron-left"></i> </a>
            </li>
            <li> <a class="pagination__link" href="~/Areas/Admin/">...</a> </li>
            @for (int j = 1; j <= ViewBag.PageCount; j++)
            {
                <li> <a class="pagination__link @(j==ViewBag.CurrentPage ?"pagination__link--active":"")" asp-area="admin" asp-controller="NewsName" asp-action="index" asp-route-page="@j">@j</a> </li>
            }
            <li> <a class="pagination__link" href="~/Areas/Admin/">...</a> </li>
            <li>
                <a class="pagination__link" asp-area="admin" asp-controller="NewsName" asp-action="index" asp-route-page="@(ViewBag.CurrentPage>=ViewBag.PageCount?ViewBag.PageCount:ViewBag.CurrentPage + 1)"> <i class="w-4 h-4" data-feather="chevron-right"></i> </a>
            </li>
            <li>
                <a class="pagination__link" asp-area="admin" asp-controller="NewsName" asp-action="index" asp-route-page="@ViewBag.PageCount"> <i class="w-4 h-4" data-feather="chevrons-right"></i> </a>
            </li>
        </ul>

    </div>
    <!-- END: Pagination -->
</div>
<!-- BEGIN: Delete Confirmation Modal -->
<div class="modal" id="delete-confirmation-modal">
    <div class="modal__content">
        <div class="p-5 text-center">
            <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
            <div class="text-3xl mt-5">Are you sure?</div>
            <div class="text-gray-600 mt-2">Do you really want to delete these records? This process cannot be undone.</div>
        </div>
        <div class="px-5 pb-8 text-center">
            <a asp-area="Admin" asp-controller="NewsName" asp-action="index" data-dismiss="modal" class="button w-24 border text-gray-700 mr-1">Cancel</a>
            <button type="button" class="button w-24 bg-theme-6 text-white">Delete</button>
        </div>
    </div>
</div>

Justica2/Justica2/Areas/Admin/Views/NewsName/Update.cshtml
@model NewsName
@{
    ViewData["Title"] = "Update";
}

<div class="intro-y flex items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Update News Name
    </h2>
</div>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 lg:col-span-6">
        <!-- BEGIN: Form Layout -->
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" style="color:red; margin-bottom:30px;"></div>
            <div class="intro-y box p-5">
                <input asp-for="Id" hidden />
                <div>
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="input w-full border mt-2">
                </div>
                <div class="mt-3">
                    <label asp-for="NewsId">Practice Area Name</label>
                    <div class="mt-2">
                        <select asp-for="NewsId" asp-items="@(new SelectList(ViewBag.News, "Id", "Name"))" data-placeholder="Select your favorite actors" class="select2 w-full">
                            <option selected="" disabled>Select Category</option>
                        </select>
                    </div>
                </div>
                <div class="text-right mt-5">
                    <a asp-area="admin" asp-controller="NewsName" asp-action="index" class="button w-24 border text-gray-700 mr-1">Cancel</a>
                    <button type="submit" class="button w-24 bg-theme-1 text-white">Update</button>
                </div>
            </div>
        </form>
        <!-- END: Form Layout -->
    </div>
</div>